// DO NOT EDIT. generated by github.com/tinywasm/orm

package user

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/orm"
)

func (m *User) ModelName() string {
	return "user"
}

var _schemaUser = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "email", Type: fmt.FieldText, DB: &fmt.FieldDB{Unique: true}, OmitEmpty: true},
		{Name: "name", Type: fmt.FieldText},
		{Name: "phone", Type: fmt.FieldText, OmitEmpty: true},
		{Name: "status", Type: fmt.FieldText},
		{Name: "created_at", Type: fmt.FieldInt},
	}

func (m *User) Schema() []fmt.Field { return _schemaUser }

func (m *User) Pointers() []any {
	return []any{
		&m.ID,
		&m.Email,
		&m.Name,
		&m.Phone,
		&m.Status,
		&m.CreatedAt,
	}
}

var User_ = struct {
	ModelName string
	ID string
	Email string
	Name string
	Phone string
	Status string
	CreatedAt string
}{
	ModelName: "user",
	ID: "id",
	Email: "email",
	Name: "name",
	Phone: "phone",
	Status: "status",
	CreatedAt: "created_at",
}

func ReadOneUser(qb *orm.QB, model *User) (*User, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUser(qb *orm.QB) ([]*User, error) {
	var results []*User
	err := qb.ReadAll(
		func() fmt.Model { return &User{} },
		func(m fmt.Model) { results = append(results, m.(*User)) },
	)
	return results, err
}

func (m *Session) ModelName() string {
	return "session"
}

var _schemaSession = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "user_id", Type: fmt.FieldText},
		{Name: "expires_at", Type: fmt.FieldInt},
		{Name: "ip", Type: fmt.FieldText, OmitEmpty: true},
		{Name: "user_agent", Type: fmt.FieldText, OmitEmpty: true},
		{Name: "created_at", Type: fmt.FieldInt},
	}

func (m *Session) Schema() []fmt.Field { return _schemaSession }

func (m *Session) Pointers() []any {
	return []any{
		&m.ID,
		&m.UserID,
		&m.ExpiresAt,
		&m.IP,
		&m.UserAgent,
		&m.CreatedAt,
	}
}

var Session_ = struct {
	ModelName string
	ID string
	UserID string
	ExpiresAt string
	IP string
	UserAgent string
	CreatedAt string
}{
	ModelName: "session",
	ID: "id",
	UserID: "user_id",
	ExpiresAt: "expires_at",
	IP: "ip",
	UserAgent: "user_agent",
	CreatedAt: "created_at",
}

func ReadOneSession(qb *orm.QB, model *Session) (*Session, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllSession(qb *orm.QB) ([]*Session, error) {
	var results []*Session
	err := qb.ReadAll(
		func() fmt.Model { return &Session{} },
		func(m fmt.Model) { results = append(results, m.(*Session)) },
	)
	return results, err
}

func (m *LoginData) ModelName() string {
	return "login_data"
}

var _schemaLoginData = []fmt.Field{
		{Name: "email", Type: fmt.FieldText},
		{Name: "password", Type: fmt.FieldText},
	}

func (m *LoginData) Schema() []fmt.Field { return _schemaLoginData }

func (m *LoginData) Pointers() []any {
	return []any{
		&m.Email,
		&m.Password,
	}
}

var LoginData_ = struct {
	ModelName string
	Email string
	Password string
}{
	ModelName: "login_data",
	Email: "email",
	Password: "password",
}

func ReadOneLoginData(qb *orm.QB, model *LoginData) (*LoginData, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllLoginData(qb *orm.QB) ([]*LoginData, error) {
	var results []*LoginData
	err := qb.ReadAll(
		func() fmt.Model { return &LoginData{} },
		func(m fmt.Model) { results = append(results, m.(*LoginData)) },
	)
	return results, err
}

func (m *RegisterData) ModelName() string {
	return "register_data"
}

var _schemaRegisterData = []fmt.Field{
		{Name: "name", Type: fmt.FieldText},
		{Name: "email", Type: fmt.FieldText},
		{Name: "password", Type: fmt.FieldText},
		{Name: "phone", Type: fmt.FieldText},
	}

func (m *RegisterData) Schema() []fmt.Field { return _schemaRegisterData }

func (m *RegisterData) Pointers() []any {
	return []any{
		&m.Name,
		&m.Email,
		&m.Password,
		&m.Phone,
	}
}

var RegisterData_ = struct {
	ModelName string
	Name string
	Email string
	Password string
	Phone string
}{
	ModelName: "register_data",
	Name: "name",
	Email: "email",
	Password: "password",
	Phone: "phone",
}

func ReadOneRegisterData(qb *orm.QB, model *RegisterData) (*RegisterData, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRegisterData(qb *orm.QB) ([]*RegisterData, error) {
	var results []*RegisterData
	err := qb.ReadAll(
		func() fmt.Model { return &RegisterData{} },
		func(m fmt.Model) { results = append(results, m.(*RegisterData)) },
	)
	return results, err
}

func (m *ProfileData) ModelName() string {
	return "profile_data"
}

var _schemaProfileData = []fmt.Field{
		{Name: "name", Type: fmt.FieldText},
		{Name: "phone", Type: fmt.FieldText},
	}

func (m *ProfileData) Schema() []fmt.Field { return _schemaProfileData }

func (m *ProfileData) Pointers() []any {
	return []any{
		&m.Name,
		&m.Phone,
	}
}

var ProfileData_ = struct {
	ModelName string
	Name string
	Phone string
}{
	ModelName: "profile_data",
	Name: "name",
	Phone: "phone",
}

func ReadOneProfileData(qb *orm.QB, model *ProfileData) (*ProfileData, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllProfileData(qb *orm.QB) ([]*ProfileData, error) {
	var results []*ProfileData
	err := qb.ReadAll(
		func() fmt.Model { return &ProfileData{} },
		func(m fmt.Model) { results = append(results, m.(*ProfileData)) },
	)
	return results, err
}

func (m *PasswordData) ModelName() string {
	return "password_data"
}

var _schemaPasswordData = []fmt.Field{
		{Name: "current", Type: fmt.FieldText},
		{Name: "new", Type: fmt.FieldText},
		{Name: "confirm", Type: fmt.FieldText},
	}

func (m *PasswordData) Schema() []fmt.Field { return _schemaPasswordData }

func (m *PasswordData) Pointers() []any {
	return []any{
		&m.Current,
		&m.New,
		&m.Confirm,
	}
}

var PasswordData_ = struct {
	ModelName string
	Current string
	New string
	Confirm string
}{
	ModelName: "password_data",
	Current: "current",
	New: "new",
	Confirm: "confirm",
}

func ReadOnePasswordData(qb *orm.QB, model *PasswordData) (*PasswordData, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPasswordData(qb *orm.QB) ([]*PasswordData, error) {
	var results []*PasswordData
	err := qb.ReadAll(
		func() fmt.Model { return &PasswordData{} },
		func(m fmt.Model) { results = append(results, m.(*PasswordData)) },
	)
	return results, err
}

func (m *Identity) ModelName() string {
	return "identity"
}

var _schemaIdentity = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "user_id", Type: fmt.FieldText},
		{Name: "provider", Type: fmt.FieldText},
		{Name: "provider_id", Type: fmt.FieldText},
		{Name: "email", Type: fmt.FieldText, OmitEmpty: true},
		{Name: "created_at", Type: fmt.FieldInt},
	}

func (m *Identity) Schema() []fmt.Field { return _schemaIdentity }

func (m *Identity) Pointers() []any {
	return []any{
		&m.ID,
		&m.UserID,
		&m.Provider,
		&m.ProviderID,
		&m.Email,
		&m.CreatedAt,
	}
}

var Identity_ = struct {
	ModelName string
	ID string
	UserID string
	Provider string
	ProviderID string
	Email string
	CreatedAt string
}{
	ModelName: "identity",
	ID: "id",
	UserID: "user_id",
	Provider: "provider",
	ProviderID: "provider_id",
	Email: "email",
	CreatedAt: "created_at",
}

func ReadOneIdentity(qb *orm.QB, model *Identity) (*Identity, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllIdentity(qb *orm.QB) ([]*Identity, error) {
	var results []*Identity
	err := qb.ReadAll(
		func() fmt.Model { return &Identity{} },
		func(m fmt.Model) { results = append(results, m.(*Identity)) },
	)
	return results, err
}

func (m *Role) ModelName() string {
	return "role"
}

var _schemaRole = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "code", Type: fmt.FieldText},
		{Name: "name", Type: fmt.FieldText},
		{Name: "description", Type: fmt.FieldText},
	}

func (m *Role) Schema() []fmt.Field { return _schemaRole }

func (m *Role) Pointers() []any {
	return []any{
		&m.ID,
		&m.Code,
		&m.Name,
		&m.Description,
	}
}

var Role_ = struct {
	ModelName string
	ID string
	Code string
	Name string
	Description string
}{
	ModelName: "role",
	ID: "id",
	Code: "code",
	Name: "name",
	Description: "description",
}

func ReadOneRole(qb *orm.QB, model *Role) (*Role, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRole(qb *orm.QB) ([]*Role, error) {
	var results []*Role
	err := qb.ReadAll(
		func() fmt.Model { return &Role{} },
		func(m fmt.Model) { results = append(results, m.(*Role)) },
	)
	return results, err
}

func (m *UserRole) ModelName() string {
	return "user_role"
}

var _schemaUserRole = []fmt.Field{
		{Name: "user_id", Type: fmt.FieldText},
		{Name: "role_id", Type: fmt.FieldText},
	}

func (m *UserRole) Schema() []fmt.Field { return _schemaUserRole }

func (m *UserRole) Pointers() []any {
	return []any{
		&m.UserID,
		&m.RoleID,
	}
}

var UserRole_ = struct {
	ModelName string
	UserID string
	RoleID string
}{
	ModelName: "user_role",
	UserID: "user_id",
	RoleID: "role_id",
}

func ReadOneUserRole(qb *orm.QB, model *UserRole) (*UserRole, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUserRole(qb *orm.QB) ([]*UserRole, error) {
	var results []*UserRole
	err := qb.ReadAll(
		func() fmt.Model { return &UserRole{} },
		func(m fmt.Model) { results = append(results, m.(*UserRole)) },
	)
	return results, err
}

func (m *Permission) ModelName() string {
	return "permission"
}

var _schemaPermission = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "name", Type: fmt.FieldText},
		{Name: "resource", Type: fmt.FieldText},
		{Name: "action", Type: fmt.FieldText},
	}

func (m *Permission) Schema() []fmt.Field { return _schemaPermission }

func (m *Permission) Pointers() []any {
	return []any{
		&m.ID,
		&m.Name,
		&m.Resource,
		&m.Action,
	}
}

var Permission_ = struct {
	ModelName string
	ID string
	Name string
	Resource string
	Action string
}{
	ModelName: "permission",
	ID: "id",
	Name: "name",
	Resource: "resource",
	Action: "action",
}

func ReadOnePermission(qb *orm.QB, model *Permission) (*Permission, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPermission(qb *orm.QB) ([]*Permission, error) {
	var results []*Permission
	err := qb.ReadAll(
		func() fmt.Model { return &Permission{} },
		func(m fmt.Model) { results = append(results, m.(*Permission)) },
	)
	return results, err
}

func (m *RolePermission) ModelName() string {
	return "role_permission"
}

var _schemaRolePermission = []fmt.Field{
		{Name: "role_id", Type: fmt.FieldText},
		{Name: "permission_id", Type: fmt.FieldText},
	}

func (m *RolePermission) Schema() []fmt.Field { return _schemaRolePermission }

func (m *RolePermission) Pointers() []any {
	return []any{
		&m.RoleID,
		&m.PermissionID,
	}
}

var RolePermission_ = struct {
	ModelName string
	RoleID string
	PermissionID string
}{
	ModelName: "role_permission",
	RoleID: "role_id",
	PermissionID: "permission_id",
}

func ReadOneRolePermission(qb *orm.QB, model *RolePermission) (*RolePermission, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRolePermission(qb *orm.QB) ([]*RolePermission, error) {
	var results []*RolePermission
	err := qb.ReadAll(
		func() fmt.Model { return &RolePermission{} },
		func(m fmt.Model) { results = append(results, m.(*RolePermission)) },
	)
	return results, err
}

func (m *LANIP) ModelName() string {
	return "lanip"
}

var _schemaLANIP = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "user_id", Type: fmt.FieldText},
		{Name: "ip", Type: fmt.FieldText},
		{Name: "label", Type: fmt.FieldText},
		{Name: "created_at", Type: fmt.FieldInt},
	}

func (m *LANIP) Schema() []fmt.Field { return _schemaLANIP }

func (m *LANIP) Pointers() []any {
	return []any{
		&m.ID,
		&m.UserID,
		&m.IP,
		&m.Label,
		&m.CreatedAt,
	}
}

var LANIP_ = struct {
	ModelName string
	ID string
	UserID string
	IP string
	Label string
	CreatedAt string
}{
	ModelName: "lanip",
	ID: "id",
	UserID: "user_id",
	IP: "ip",
	Label: "label",
	CreatedAt: "created_at",
}

func ReadOneLANIP(qb *orm.QB, model *LANIP) (*LANIP, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllLANIP(qb *orm.QB) ([]*LANIP, error) {
	var results []*LANIP
	err := qb.ReadAll(
		func() fmt.Model { return &LANIP{} },
		func(m fmt.Model) { results = append(results, m.(*LANIP)) },
	)
	return results, err
}

func (m *OAuthState) ModelName() string {
	return "oauth_state"
}

var _schemaOAuthState = []fmt.Field{
		{Name: "state", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "provider", Type: fmt.FieldText},
		{Name: "expires_at", Type: fmt.FieldInt},
		{Name: "created_at", Type: fmt.FieldInt},
	}

func (m *OAuthState) Schema() []fmt.Field { return _schemaOAuthState }

func (m *OAuthState) Pointers() []any {
	return []any{
		&m.State,
		&m.Provider,
		&m.ExpiresAt,
		&m.CreatedAt,
	}
}

var OAuthState_ = struct {
	ModelName string
	State string
	Provider string
	ExpiresAt string
	CreatedAt string
}{
	ModelName: "oauth_state",
	State: "state",
	Provider: "provider",
	ExpiresAt: "expires_at",
	CreatedAt: "created_at",
}

func ReadOneOAuthState(qb *orm.QB, model *OAuthState) (*OAuthState, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllOAuthState(qb *orm.QB) ([]*OAuthState, error) {
	var results []*OAuthState
	err := qb.ReadAll(
		func() fmt.Model { return &OAuthState{} },
		func(m fmt.Model) { results = append(results, m.(*OAuthState)) },
	)
	return results, err
}

