// DO NOT EDIT. generated by github.com/tinywasm/orm

package user

import (
	"github.com/tinywasm/model"
	"github.com/tinywasm/orm"
)

func (m *User) ModelName() string {
	return "user"
}

var _schemaUser = []model.Field{
		{Name: "id", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
		{Name: "email", Type: model.FieldText, DB: &model.FieldDB{Unique: true}},
		{Name: "name", Type: model.FieldText},
		{Name: "phone", Type: model.FieldText},
		{Name: "status", Type: model.FieldText},
		{Name: "created_at", Type: model.FieldInt},
	}

func (m *User) Schema() []model.Field { return _schemaUser }

func (m *User) Pointers() []any { return []any{&m.ID, &m.Email, &m.Name, &m.Phone, &m.Status, &m.CreatedAt} }

func (m *User) IsNil() bool { return m == nil }

func (m *User) EncodeFields(w model.FieldWriter) {
	w.String("id", m.ID)
	w.String("email", m.Email)
	w.String("name", m.Name)
	w.String("phone", m.Phone)
	w.String("status", m.Status)
	w.Int("created_at", int64(m.CreatedAt))
}

func (m *User) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("phone"); ok { m.Phone = v }
	if v, ok := r.String("status"); ok { m.Status = v }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = int64(v) }
}

type UserList []*User

func (s *UserList) Schema() []model.Field { return nil }
func (s *UserList) Pointers() []any     { return nil }
func (s *UserList) Len() int             { return len(*s) }
func (s *UserList) At(i int) model.Fielder { return (*s)[i] }
func (s *UserList) Append() model.Fielder  { v := &User{}; *s = append(*s, v); return v }
func (s *UserList) IsNil() bool          { return s == nil }
func (s *UserList) EncodeFields(_ model.FieldWriter) {}
func (s *UserList) DecodeFields(_ model.FieldReader) {}

var User_ = struct {
	ID string
	Email string
	Name string
	Phone string
	Status string
	CreatedAt string
}{
	ID: "id",
	Email: "email",
	Name: "name",
	Phone: "phone",
	Status: "status",
	CreatedAt: "created_at",
}

func ReadOneUser(qb *orm.QB, model *User) (*User, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUser(qb *orm.QB) (UserList, error) {
	var results UserList
	err := qb.ReadAll(
		func() model.Model { return &User{} },
		func(m model.Model) { results = append(results, m.(*User)) },
	)
	return results, err
}

func (m *Session) ModelName() string {
	return "session"
}

var _schemaSession = []model.Field{
		{Name: "id", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
		{Name: "user_id", Type: model.FieldText},
		{Name: "expires_at", Type: model.FieldInt},
		{Name: "ip", Type: model.FieldText},
		{Name: "user_agent", Type: model.FieldText},
		{Name: "created_at", Type: model.FieldInt},
	}

func (m *Session) Schema() []model.Field { return _schemaSession }

func (m *Session) Pointers() []any { return []any{&m.ID, &m.UserID, &m.ExpiresAt, &m.IP, &m.UserAgent, &m.CreatedAt} }

func (m *Session) IsNil() bool { return m == nil }

func (m *Session) EncodeFields(w model.FieldWriter) {
	w.String("id", m.ID)
	w.String("user_id", m.UserID)
	w.Int("expires_at", int64(m.ExpiresAt))
	w.String("ip", m.IP)
	w.String("user_agent", m.UserAgent)
	w.Int("created_at", int64(m.CreatedAt))
}

func (m *Session) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.String("user_id"); ok { m.UserID = v }
	if v, ok := r.Int("expires_at"); ok { m.ExpiresAt = int64(v) }
	if v, ok := r.String("ip"); ok { m.IP = v }
	if v, ok := r.String("user_agent"); ok { m.UserAgent = v }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = int64(v) }
}

type SessionList []*Session

func (s *SessionList) Schema() []model.Field { return nil }
func (s *SessionList) Pointers() []any     { return nil }
func (s *SessionList) Len() int             { return len(*s) }
func (s *SessionList) At(i int) model.Fielder { return (*s)[i] }
func (s *SessionList) Append() model.Fielder  { v := &Session{}; *s = append(*s, v); return v }
func (s *SessionList) IsNil() bool          { return s == nil }
func (s *SessionList) EncodeFields(_ model.FieldWriter) {}
func (s *SessionList) DecodeFields(_ model.FieldReader) {}

var Session_ = struct {
	ID string
	UserID string
	ExpiresAt string
	IP string
	UserAgent string
	CreatedAt string
}{
	ID: "id",
	UserID: "user_id",
	ExpiresAt: "expires_at",
	IP: "ip",
	UserAgent: "user_agent",
	CreatedAt: "created_at",
}

func ReadOneSession(qb *orm.QB, model *Session) (*Session, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllSession(qb *orm.QB) (SessionList, error) {
	var results SessionList
	err := qb.ReadAll(
		func() model.Model { return &Session{} },
		func(m model.Model) { results = append(results, m.(*Session)) },
	)
	return results, err
}

func (m *Session) SchemaExt() []orm.FieldExt {
	return []orm.FieldExt{
		{Field: _schemaSession[1], Ref: "users", RefColumn: "", OnDelete: ""},
	}
}

func (m *LoginData) ModelName() string {
	return "login_data"
}

var _schemaLoginData = []model.Field{
		{Name: "email", Type: model.FieldText},
		{Name: "password", Type: model.FieldText},
	}

func (m *LoginData) Schema() []model.Field { return _schemaLoginData }

func (m *LoginData) Pointers() []any { return []any{&m.Email, &m.Password} }

func (m *LoginData) IsNil() bool { return m == nil }

func (m *LoginData) EncodeFields(w model.FieldWriter) {
	w.String("email", m.Email)
	w.String("password", m.Password)
}

func (m *LoginData) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.String("password"); ok { m.Password = v }
}

type LoginDataList []*LoginData

func (s *LoginDataList) Schema() []model.Field { return nil }
func (s *LoginDataList) Pointers() []any     { return nil }
func (s *LoginDataList) Len() int             { return len(*s) }
func (s *LoginDataList) At(i int) model.Fielder { return (*s)[i] }
func (s *LoginDataList) Append() model.Fielder  { v := &LoginData{}; *s = append(*s, v); return v }
func (s *LoginDataList) IsNil() bool          { return s == nil }
func (s *LoginDataList) EncodeFields(_ model.FieldWriter) {}
func (s *LoginDataList) DecodeFields(_ model.FieldReader) {}

func (m *RegisterData) ModelName() string {
	return "register_data"
}

var _schemaRegisterData = []model.Field{
		{Name: "name", Type: model.FieldText},
		{Name: "email", Type: model.FieldText},
		{Name: "password", Type: model.FieldText},
		{Name: "phone", Type: model.FieldText},
	}

func (m *RegisterData) Schema() []model.Field { return _schemaRegisterData }

func (m *RegisterData) Pointers() []any { return []any{&m.Name, &m.Email, &m.Password, &m.Phone} }

func (m *RegisterData) IsNil() bool { return m == nil }

func (m *RegisterData) EncodeFields(w model.FieldWriter) {
	w.String("name", m.Name)
	w.String("email", m.Email)
	w.String("password", m.Password)
	w.String("phone", m.Phone)
}

func (m *RegisterData) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.String("password"); ok { m.Password = v }
	if v, ok := r.String("phone"); ok { m.Phone = v }
}

type RegisterDataList []*RegisterData

func (s *RegisterDataList) Schema() []model.Field { return nil }
func (s *RegisterDataList) Pointers() []any     { return nil }
func (s *RegisterDataList) Len() int             { return len(*s) }
func (s *RegisterDataList) At(i int) model.Fielder { return (*s)[i] }
func (s *RegisterDataList) Append() model.Fielder  { v := &RegisterData{}; *s = append(*s, v); return v }
func (s *RegisterDataList) IsNil() bool          { return s == nil }
func (s *RegisterDataList) EncodeFields(_ model.FieldWriter) {}
func (s *RegisterDataList) DecodeFields(_ model.FieldReader) {}

func (m *ProfileData) ModelName() string {
	return "profile_data"
}

var _schemaProfileData = []model.Field{
		{Name: "name", Type: model.FieldText},
		{Name: "phone", Type: model.FieldText},
	}

func (m *ProfileData) Schema() []model.Field { return _schemaProfileData }

func (m *ProfileData) Pointers() []any { return []any{&m.Name, &m.Phone} }

func (m *ProfileData) IsNil() bool { return m == nil }

func (m *ProfileData) EncodeFields(w model.FieldWriter) {
	w.String("name", m.Name)
	w.String("phone", m.Phone)
}

func (m *ProfileData) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("phone"); ok { m.Phone = v }
}

type ProfileDataList []*ProfileData

func (s *ProfileDataList) Schema() []model.Field { return nil }
func (s *ProfileDataList) Pointers() []any     { return nil }
func (s *ProfileDataList) Len() int             { return len(*s) }
func (s *ProfileDataList) At(i int) model.Fielder { return (*s)[i] }
func (s *ProfileDataList) Append() model.Fielder  { v := &ProfileData{}; *s = append(*s, v); return v }
func (s *ProfileDataList) IsNil() bool          { return s == nil }
func (s *ProfileDataList) EncodeFields(_ model.FieldWriter) {}
func (s *ProfileDataList) DecodeFields(_ model.FieldReader) {}

func (m *PasswordData) ModelName() string {
	return "password_data"
}

var _schemaPasswordData = []model.Field{
		{Name: "current", Type: model.FieldText},
		{Name: "new", Type: model.FieldText},
		{Name: "confirm", Type: model.FieldText},
	}

func (m *PasswordData) Schema() []model.Field { return _schemaPasswordData }

func (m *PasswordData) Pointers() []any { return []any{&m.Current, &m.New, &m.Confirm} }

func (m *PasswordData) IsNil() bool { return m == nil }

func (m *PasswordData) EncodeFields(w model.FieldWriter) {
	w.String("current", m.Current)
	w.String("new", m.New)
	w.String("confirm", m.Confirm)
}

func (m *PasswordData) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("current"); ok { m.Current = v }
	if v, ok := r.String("new"); ok { m.New = v }
	if v, ok := r.String("confirm"); ok { m.Confirm = v }
}

type PasswordDataList []*PasswordData

func (s *PasswordDataList) Schema() []model.Field { return nil }
func (s *PasswordDataList) Pointers() []any     { return nil }
func (s *PasswordDataList) Len() int             { return len(*s) }
func (s *PasswordDataList) At(i int) model.Fielder { return (*s)[i] }
func (s *PasswordDataList) Append() model.Fielder  { v := &PasswordData{}; *s = append(*s, v); return v }
func (s *PasswordDataList) IsNil() bool          { return s == nil }
func (s *PasswordDataList) EncodeFields(_ model.FieldWriter) {}
func (s *PasswordDataList) DecodeFields(_ model.FieldReader) {}

func (m *Identity) ModelName() string {
	return "identity"
}

var _schemaIdentity = []model.Field{
		{Name: "id", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
		{Name: "user_id", Type: model.FieldText},
		{Name: "provider", Type: model.FieldText},
		{Name: "provider_id", Type: model.FieldText},
		{Name: "email", Type: model.FieldText},
		{Name: "created_at", Type: model.FieldInt},
	}

func (m *Identity) Schema() []model.Field { return _schemaIdentity }

func (m *Identity) Pointers() []any { return []any{&m.ID, &m.UserID, &m.Provider, &m.ProviderID, &m.Email, &m.CreatedAt} }

func (m *Identity) IsNil() bool { return m == nil }

func (m *Identity) EncodeFields(w model.FieldWriter) {
	w.String("id", m.ID)
	w.String("user_id", m.UserID)
	w.String("provider", m.Provider)
	w.String("provider_id", m.ProviderID)
	w.String("email", m.Email)
	w.Int("created_at", int64(m.CreatedAt))
}

func (m *Identity) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.String("user_id"); ok { m.UserID = v }
	if v, ok := r.String("provider"); ok { m.Provider = v }
	if v, ok := r.String("provider_id"); ok { m.ProviderID = v }
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = int64(v) }
}

type IdentityList []*Identity

func (s *IdentityList) Schema() []model.Field { return nil }
func (s *IdentityList) Pointers() []any     { return nil }
func (s *IdentityList) Len() int             { return len(*s) }
func (s *IdentityList) At(i int) model.Fielder { return (*s)[i] }
func (s *IdentityList) Append() model.Fielder  { v := &Identity{}; *s = append(*s, v); return v }
func (s *IdentityList) IsNil() bool          { return s == nil }
func (s *IdentityList) EncodeFields(_ model.FieldWriter) {}
func (s *IdentityList) DecodeFields(_ model.FieldReader) {}

var Identity_ = struct {
	ID string
	UserID string
	Provider string
	ProviderID string
	Email string
	CreatedAt string
}{
	ID: "id",
	UserID: "user_id",
	Provider: "provider",
	ProviderID: "provider_id",
	Email: "email",
	CreatedAt: "created_at",
}

func ReadOneIdentity(qb *orm.QB, model *Identity) (*Identity, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllIdentity(qb *orm.QB) (IdentityList, error) {
	var results IdentityList
	err := qb.ReadAll(
		func() model.Model { return &Identity{} },
		func(m model.Model) { results = append(results, m.(*Identity)) },
	)
	return results, err
}

func (m *Identity) SchemaExt() []orm.FieldExt {
	return []orm.FieldExt{
		{Field: _schemaIdentity[1], Ref: "users", RefColumn: "", OnDelete: ""},
	}
}

func (m *Role) ModelName() string {
	return "role"
}

var _schemaRole = []model.Field{
		{Name: "id", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
		{Name: "code", Type: model.FieldText},
		{Name: "name", Type: model.FieldText},
		{Name: "description", Type: model.FieldText},
	}

func (m *Role) Schema() []model.Field { return _schemaRole }

func (m *Role) Pointers() []any { return []any{&m.ID, &m.Code, &m.Name, &m.Description} }

func (m *Role) IsNil() bool { return m == nil }

func (m *Role) EncodeFields(w model.FieldWriter) {
	w.String("id", m.ID)
	w.String("code", m.Code)
	w.String("name", m.Name)
	w.String("description", m.Description)
}

func (m *Role) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.String("code"); ok { m.Code = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("description"); ok { m.Description = v }
}

type RoleList []*Role

func (s *RoleList) Schema() []model.Field { return nil }
func (s *RoleList) Pointers() []any     { return nil }
func (s *RoleList) Len() int             { return len(*s) }
func (s *RoleList) At(i int) model.Fielder { return (*s)[i] }
func (s *RoleList) Append() model.Fielder  { v := &Role{}; *s = append(*s, v); return v }
func (s *RoleList) IsNil() bool          { return s == nil }
func (s *RoleList) EncodeFields(_ model.FieldWriter) {}
func (s *RoleList) DecodeFields(_ model.FieldReader) {}

var Role_ = struct {
	ID string
	Code string
	Name string
	Description string
}{
	ID: "id",
	Code: "code",
	Name: "name",
	Description: "description",
}

func ReadOneRole(qb *orm.QB, model *Role) (*Role, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRole(qb *orm.QB) (RoleList, error) {
	var results RoleList
	err := qb.ReadAll(
		func() model.Model { return &Role{} },
		func(m model.Model) { results = append(results, m.(*Role)) },
	)
	return results, err
}

func (m *UserRole) ModelName() string {
	return "user_role"
}

var _schemaUserRole = []model.Field{
		{Name: "user_id", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
		{Name: "role_id", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
	}

func (m *UserRole) Schema() []model.Field { return _schemaUserRole }

func (m *UserRole) Pointers() []any { return []any{&m.UserID, &m.RoleID} }

func (m *UserRole) IsNil() bool { return m == nil }

func (m *UserRole) EncodeFields(w model.FieldWriter) {
	w.String("user_id", m.UserID)
	w.String("role_id", m.RoleID)
}

func (m *UserRole) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("user_id"); ok { m.UserID = v }
	if v, ok := r.String("role_id"); ok { m.RoleID = v }
}

type UserRoleList []*UserRole

func (s *UserRoleList) Schema() []model.Field { return nil }
func (s *UserRoleList) Pointers() []any     { return nil }
func (s *UserRoleList) Len() int             { return len(*s) }
func (s *UserRoleList) At(i int) model.Fielder { return (*s)[i] }
func (s *UserRoleList) Append() model.Fielder  { v := &UserRole{}; *s = append(*s, v); return v }
func (s *UserRoleList) IsNil() bool          { return s == nil }
func (s *UserRoleList) EncodeFields(_ model.FieldWriter) {}
func (s *UserRoleList) DecodeFields(_ model.FieldReader) {}

var UserRole_ = struct {
	UserID string
	RoleID string
}{
	UserID: "user_id",
	RoleID: "role_id",
}

func ReadOneUserRole(qb *orm.QB, model *UserRole) (*UserRole, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUserRole(qb *orm.QB) (UserRoleList, error) {
	var results UserRoleList
	err := qb.ReadAll(
		func() model.Model { return &UserRole{} },
		func(m model.Model) { results = append(results, m.(*UserRole)) },
	)
	return results, err
}

func (m *UserRole) SchemaExt() []orm.FieldExt {
	return []orm.FieldExt{
		{Field: _schemaUserRole[0], Ref: "users", RefColumn: "", OnDelete: ""},
		{Field: _schemaUserRole[1], Ref: "roles", RefColumn: "", OnDelete: ""},
	}
}

func (m *Permission) ModelName() string {
	return "permission"
}

var _schemaPermission = []model.Field{
		{Name: "id", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
		{Name: "name", Type: model.FieldText},
		{Name: "resource", Type: model.FieldText},
		{Name: "action", Type: model.FieldText},
	}

func (m *Permission) Schema() []model.Field { return _schemaPermission }

func (m *Permission) Pointers() []any { return []any{&m.ID, &m.Name, &m.Resource, &m.Action} }

func (m *Permission) IsNil() bool { return m == nil }

func (m *Permission) EncodeFields(w model.FieldWriter) {
	w.String("id", m.ID)
	w.String("name", m.Name)
	w.String("resource", m.Resource)
	w.String("action", m.Action)
}

func (m *Permission) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("resource"); ok { m.Resource = v }
	if v, ok := r.String("action"); ok { m.Action = v }
}

type PermissionList []*Permission

func (s *PermissionList) Schema() []model.Field { return nil }
func (s *PermissionList) Pointers() []any     { return nil }
func (s *PermissionList) Len() int             { return len(*s) }
func (s *PermissionList) At(i int) model.Fielder { return (*s)[i] }
func (s *PermissionList) Append() model.Fielder  { v := &Permission{}; *s = append(*s, v); return v }
func (s *PermissionList) IsNil() bool          { return s == nil }
func (s *PermissionList) EncodeFields(_ model.FieldWriter) {}
func (s *PermissionList) DecodeFields(_ model.FieldReader) {}

var Permission_ = struct {
	ID string
	Name string
	Resource string
	Action string
}{
	ID: "id",
	Name: "name",
	Resource: "resource",
	Action: "action",
}

func ReadOnePermission(qb *orm.QB, model *Permission) (*Permission, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPermission(qb *orm.QB) (PermissionList, error) {
	var results PermissionList
	err := qb.ReadAll(
		func() model.Model { return &Permission{} },
		func(m model.Model) { results = append(results, m.(*Permission)) },
	)
	return results, err
}

func (m *RolePermission) ModelName() string {
	return "role_permission"
}

var _schemaRolePermission = []model.Field{
		{Name: "role_id", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
		{Name: "permission_id", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
	}

func (m *RolePermission) Schema() []model.Field { return _schemaRolePermission }

func (m *RolePermission) Pointers() []any { return []any{&m.RoleID, &m.PermissionID} }

func (m *RolePermission) IsNil() bool { return m == nil }

func (m *RolePermission) EncodeFields(w model.FieldWriter) {
	w.String("role_id", m.RoleID)
	w.String("permission_id", m.PermissionID)
}

func (m *RolePermission) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("role_id"); ok { m.RoleID = v }
	if v, ok := r.String("permission_id"); ok { m.PermissionID = v }
}

type RolePermissionList []*RolePermission

func (s *RolePermissionList) Schema() []model.Field { return nil }
func (s *RolePermissionList) Pointers() []any     { return nil }
func (s *RolePermissionList) Len() int             { return len(*s) }
func (s *RolePermissionList) At(i int) model.Fielder { return (*s)[i] }
func (s *RolePermissionList) Append() model.Fielder  { v := &RolePermission{}; *s = append(*s, v); return v }
func (s *RolePermissionList) IsNil() bool          { return s == nil }
func (s *RolePermissionList) EncodeFields(_ model.FieldWriter) {}
func (s *RolePermissionList) DecodeFields(_ model.FieldReader) {}

var RolePermission_ = struct {
	RoleID string
	PermissionID string
}{
	RoleID: "role_id",
	PermissionID: "permission_id",
}

func ReadOneRolePermission(qb *orm.QB, model *RolePermission) (*RolePermission, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRolePermission(qb *orm.QB) (RolePermissionList, error) {
	var results RolePermissionList
	err := qb.ReadAll(
		func() model.Model { return &RolePermission{} },
		func(m model.Model) { results = append(results, m.(*RolePermission)) },
	)
	return results, err
}

func (m *RolePermission) SchemaExt() []orm.FieldExt {
	return []orm.FieldExt{
		{Field: _schemaRolePermission[0], Ref: "roles", RefColumn: "", OnDelete: ""},
		{Field: _schemaRolePermission[1], Ref: "permissions", RefColumn: "", OnDelete: ""},
	}
}

func (m *LANIP) ModelName() string {
	return "lanip"
}

var _schemaLANIP = []model.Field{
		{Name: "id", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
		{Name: "user_id", Type: model.FieldText},
		{Name: "ip", Type: model.FieldText},
		{Name: "label", Type: model.FieldText},
		{Name: "created_at", Type: model.FieldInt},
	}

func (m *LANIP) Schema() []model.Field { return _schemaLANIP }

func (m *LANIP) Pointers() []any { return []any{&m.ID, &m.UserID, &m.IP, &m.Label, &m.CreatedAt} }

func (m *LANIP) IsNil() bool { return m == nil }

func (m *LANIP) EncodeFields(w model.FieldWriter) {
	w.String("id", m.ID)
	w.String("user_id", m.UserID)
	w.String("ip", m.IP)
	w.String("label", m.Label)
	w.Int("created_at", int64(m.CreatedAt))
}

func (m *LANIP) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.ID = v }
	if v, ok := r.String("user_id"); ok { m.UserID = v }
	if v, ok := r.String("ip"); ok { m.IP = v }
	if v, ok := r.String("label"); ok { m.Label = v }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = int64(v) }
}

type LANIPList []*LANIP

func (s *LANIPList) Schema() []model.Field { return nil }
func (s *LANIPList) Pointers() []any     { return nil }
func (s *LANIPList) Len() int             { return len(*s) }
func (s *LANIPList) At(i int) model.Fielder { return (*s)[i] }
func (s *LANIPList) Append() model.Fielder  { v := &LANIP{}; *s = append(*s, v); return v }
func (s *LANIPList) IsNil() bool          { return s == nil }
func (s *LANIPList) EncodeFields(_ model.FieldWriter) {}
func (s *LANIPList) DecodeFields(_ model.FieldReader) {}

var LANIP_ = struct {
	ID string
	UserID string
	IP string
	Label string
	CreatedAt string
}{
	ID: "id",
	UserID: "user_id",
	IP: "ip",
	Label: "label",
	CreatedAt: "created_at",
}

func ReadOneLANIP(qb *orm.QB, model *LANIP) (*LANIP, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllLANIP(qb *orm.QB) (LANIPList, error) {
	var results LANIPList
	err := qb.ReadAll(
		func() model.Model { return &LANIP{} },
		func(m model.Model) { results = append(results, m.(*LANIP)) },
	)
	return results, err
}

func (m *LANIP) SchemaExt() []orm.FieldExt {
	return []orm.FieldExt{
		{Field: _schemaLANIP[1], Ref: "users", RefColumn: "", OnDelete: ""},
	}
}

func (m *OAuthState) ModelName() string {
	return "oauth_state"
}

var _schemaOAuthState = []model.Field{
		{Name: "state", Type: model.FieldText, DB: &model.FieldDB{PK: true}},
		{Name: "provider", Type: model.FieldText},
		{Name: "expires_at", Type: model.FieldInt},
		{Name: "created_at", Type: model.FieldInt},
	}

func (m *OAuthState) Schema() []model.Field { return _schemaOAuthState }

func (m *OAuthState) Pointers() []any { return []any{&m.State, &m.Provider, &m.ExpiresAt, &m.CreatedAt} }

func (m *OAuthState) IsNil() bool { return m == nil }

func (m *OAuthState) EncodeFields(w model.FieldWriter) {
	w.String("state", m.State)
	w.String("provider", m.Provider)
	w.Int("expires_at", int64(m.ExpiresAt))
	w.Int("created_at", int64(m.CreatedAt))
}

func (m *OAuthState) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("state"); ok { m.State = v }
	if v, ok := r.String("provider"); ok { m.Provider = v }
	if v, ok := r.Int("expires_at"); ok { m.ExpiresAt = int64(v) }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = int64(v) }
}

type OAuthStateList []*OAuthState

func (s *OAuthStateList) Schema() []model.Field { return nil }
func (s *OAuthStateList) Pointers() []any     { return nil }
func (s *OAuthStateList) Len() int             { return len(*s) }
func (s *OAuthStateList) At(i int) model.Fielder { return (*s)[i] }
func (s *OAuthStateList) Append() model.Fielder  { v := &OAuthState{}; *s = append(*s, v); return v }
func (s *OAuthStateList) IsNil() bool          { return s == nil }
func (s *OAuthStateList) EncodeFields(_ model.FieldWriter) {}
func (s *OAuthStateList) DecodeFields(_ model.FieldReader) {}

var OAuthState_ = struct {
	State string
	Provider string
	ExpiresAt string
	CreatedAt string
}{
	State: "state",
	Provider: "provider",
	ExpiresAt: "expires_at",
	CreatedAt: "created_at",
}

func ReadOneOAuthState(qb *orm.QB, model *OAuthState) (*OAuthState, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllOAuthState(qb *orm.QB) (OAuthStateList, error) {
	var results OAuthStateList
	err := qb.ReadAll(
		func() model.Model { return &OAuthState{} },
		func(m model.Model) { results = append(results, m.(*OAuthState)) },
	)
	return results, err
}

